[package]
name = "thag_rs"
version = "0.1.0"
authors = ["Don Forbes <don.forbes3@gmail.com>"]
description = "A versatile script runner and REPL for Rust snippets, expressions and programs"
edition = "2021"
license = "MIT OR Apache-2.0"
# Include the demo directory in the crate packagename = "thag_rs"
include = [
    "src/**",
    "Cargo.toml",
    "README.md",
    "build.rs",
    "demo/**",
    "tests/**",
]
readme = "README.md"
repository = "https://github.com/durbanlegend/thag_rs"
categories = ["command-line-utilities", "development-tools::build-utils"]
keywords = ["REPL", "command-line", "eval", "runner", "script"]

[dependencies]
bitflags = "2.6.0"
clap = { version = "4.5.16", features = ["cargo", "derive"] }
crossterm = { version = "0.28.0", features = ["use-dev-tty"] }
edit = "0.1.5"
env_logger = "0.11.5"
home = "0.5.9"
lazy_static = "1.5.0"
log = "0.4.22"
nu-ansi-term = "0.50.1"
proc-macro2 = "1.0.86"
quote = "1.0.36"
reedline = "0.33.0"
regex = "1.10.6"
serde = { version = "1.0.208", features = ["derive"] }
strum = { version = "0.26.3", features = ["derive", "phf"] }
supports-color = "3.0.0"
syn = { version = "2.0.75", features = [
    "extra-traits",
    "full",
    "visit",
    "visit-mut",
] }
termbg = "0.5.0"
toml = "0.8.19"
tui-textarea = { version = "0.6", features = ["crossterm", "search"] }
mockall = "0.13.0"
scopeguard = "1.2.0"
ratatui = "0.28.0"
cargo_toml = "0.20.4"
serde_json = "1.0.125"
serde_with = "3.9.0"

[profile.dev]
opt-level = 1 # Use slightly better optimizations.
debug = true

[profile.release]
debug = false

[lib]
name = "thag_rs"
path = "src/lib.rs"

[[bin]]
name = "thag"
path = "src/bin/thag_rs.rs"

[features]
debug-logs = []
nightly = []

[dev-dependencies]
env_logger = "0.11.5"
sequential-test = "0.2.4"
tempfile = "3.12.0"
test-generator = "0.3.1"
