[package]
name = "rs-script"
version = "0.1.0"
authors = ["Don Forbes <don.forbes3@gmail.com>"]
description = "A script runner and REPL for Rust snippets, expressions and programs"
edition = "2021"
license = "MIT OR Apache-2.0"
categories = ["command-line-utilities", "development-tools::build-utils"]
keywords = [
    "REPL",
    "command-line",
    "development",
    "eval",
    "expression-evaluator",
    "playground",
    "prototyping",
    "rapid",
    "runner",
    "script",
    "tool",
]

# Include the demo directory in the crate package
include = ["src/**", "Cargo.toml", "README.md", "demo/**"]

[dependencies]
bitflags = "2.5.0"
clap = { version = "4.5.11", features = ["cargo", "derive"] }
edit = "0.1.5"
env_logger = "0.11.3"
home = "0.5.9"
lazy_static = "1.5.0"
log = "0.4.21"
nu-ansi-term = "0.50.0"
proc-macro2 = "1.0.86"
quote = "1.0.36"
reedline = "0.33.0"
regex = "1.10.5"
serde = { version = "1.0.98", features = ["derive"] }
strum = { version = "0.26.3", features = ["derive", "phf"] }
supports-color = "3.0.0"
syn = { version = "2.0.68", features = ["extra-traits", "full", "visit"] }
termbg = "0.5.0"
toml = "0.8.14"
tui-textarea = { version = "0.5.0", features = ["crossterm", "search"] }
mockall = "0.12.1"
scopeguard = "1.2.0"
ratatui = "0.27.0"
cargo_toml = "0.20.3"

[profile.dev]
opt-level = 1 # Use slightly better optimizations.
debug = true

[profile.release]
debug = false

[lib]
name = "rs_script"
path = "src/lib.rs"

[[bin]]
name = "rs_script"
path = "src/bin/rs_script.rs"

[features]
debug-logs = []

[dev-dependencies]
env_logger = "0.11.3"
sequential-test = "0.2.4"
tempfile = "3.10.1"
test-generator = "0.3.1"
