# configuration for https://github.com/crate-ci/typos

[default.extend-words]
Iterm = "Iterm"
Noice = "Noice"
ist = "ist"
ratatui = "ratatui"

[files]
extend-exclude = ["*.png", "somefile.txt~", "styles/**"]
