- name: Cache dependencies
  uses: actions/cache@v4
  with:
    path: ~/.cache
    key: ${{ runner.os }}-build-${{ hashFiles('**/lockfiles') }}
    restore-keys: |
      ${{ runner.os }}-build-
      ${{ runner.os }}-
